<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CAL" nsURI="https://www.balticlsc.eu/model/CAL" nsPrefix="CAL">
  <eClassifiers xsi:type="ecore:EClass" name="UnitCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strength" eType="#//UnitStrength"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pins" upperBound="-1" eType="#//ComputedDataPin"
        containment="true" eOpposite="#//ComputedDataPin/call"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValues" upperBound="-1"
        eType="#//UnitParameterValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="release" lowerBound="1"
        eType="#//ComputationUnitRelease" eOpposite="#//ComputationUnitRelease/calls"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputedDataPin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" lowerBound="1" eType="#//UnitCall"
        eOpposite="#//UnitCall/pins"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//DataFlow"
        eOpposite="#//DataFlow/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" eType="#//DataFlow"
        eOpposite="#//DataFlow/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declared" lowerBound="1"
        eType="#//DeclaredDataPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ComputedDataPin" eOpposite="#//ComputedDataPin/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ComputedDataPin" eOpposite="#//ComputedDataPin/outgoing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComputationUnitStatus">
    <eLiterals name="Created"/>
    <eLiterals name="Submitted" value="1"/>
    <eLiterals name="Approved" value="2"/>
    <eLiterals name="Discontinued" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnitStrength">
    <eLiterals name="Weak"/>
    <eLiterals name="Strong" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationUnitRelease">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//UnitParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredPins" upperBound="-1"
        eType="#//DeclaredDataPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" lowerBound="1" upperBound="-1"
        eType="#//UnitCall" eOpposite="#//UnitCall/release"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//UnitParamType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnitParamType">
    <eLiterals name="Variable"/>
    <eLiterals name="Config" value="1"/>
    <eLiterals name="Port" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1"
        eType="#//UnitParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredDataPin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationApplicationRelease">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1"
        eType="#//UnitCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//DataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//ComputationUnitRelease" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
