<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CAL" nsURI="https://www.balticlsc.eu/model/CAL" nsPrefix="CAL">
  <eClassifiers xsi:type="ecore:EClass" name="UnitCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strength" eType="#//UnitStrength"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pins" upperBound="-1" eType="#//ComputedDataPin"
        changeable="false" containment="true" eOpposite="#//ComputedDataPin/call"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1" eType="#//ComputationUnitRelease"
        eOpposite="#//ComputationUnitRelease/calls"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputedDataPin" eSuperTypes="#//ConnectableDataPin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" lowerBound="1" eType="#//UnitCall"
        changeable="false" eOpposite="#//UnitCall/pins"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declared" lowerBound="1"
        eType="#//DeclaredDataPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ConnectableDataPin" eOpposite="#//ConnectableDataPin/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ConnectableDataPin" eOpposite="#//ConnectableDataPin/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComputationUnitStatus">
    <eLiterals name="Created"/>
    <eLiterals name="Submitted" value="1"/>
    <eLiterals name="Approved" value="2"/>
    <eLiterals name="Discontinued" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnitStrength">
    <eLiterals name="Weak"/>
    <eLiterals name="Strong" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationUnitRelease">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredPins" upperBound="-1"
        eType="#//DeclaredDataPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1"
        eType="#//UnitCall" eOpposite="#//UnitCall/unit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaredDataPin" eSuperTypes="#//DataPin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationApplicationRelease">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1"
        eType="#//UnitCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//DataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//ComputationUnitRelease" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationDataPins" upperBound="-1"
        eType="#//ApplicationDataPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationDataPin" eSuperTypes="#//ConnectableDataPin #//DataPin"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectableDataPin" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" eType="#//DataFlow"
        eOpposite="#//DataFlow/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//DataFlow"
        eOpposite="#//DataFlow/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPin" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataMultiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenMultiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binding" eType="#//DataBinding"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
    <eLiterals name="Single" literal="Single"/>
    <eLiterals name="Multiple" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataBinding">
    <eLiterals name="Required" literal="Required"/>
    <eLiterals name="Provided" value="1"/>
  </eClassifiers>
</ecore:EPackage>
