name: Build application
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "paper/**"

jobs:
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install packages in the root of the repository
        working-directory: ./
        run: npm install

      - name: Generate .npmrc
        run: ./scripts/generate-npmrc.sh ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run format-lint
      - run: npm run check-types
      # There are no tests yet
      # - run: npm run ci-test
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-assets
          path: frontend/build/

  build_backend:
    # Build the backend without frontend assets.
    # This way this can run in parallel to building the frontend.
    # Integrating the 2 artifacts into the final JAR happens in the `build_app` job.
    name: Build backend
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend/
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Generate Maven settings.xml
        run: >
          ./scripts/generate-settings.sh ${{ github.actor }} ${{
          secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run:
          ./mvnw --batch-mode --update-snapshots verify --settings settings.xml
      - name: Prepare JAR artifact for upload
        run: |
          mkdir staging
          find sirius-web-sample-application/target -maxdepth 1 -name "*.jar" -not -name "*-sources.jar" -exec cp {} staging/sirius-web-application.jar \;
      - name: Upload the backend JAR
        uses: actions/upload-artifact@v2
        with:
          name: sirius-web-backend
          path: backend/staging/

  build_app:
    name: Build the final application
    runs-on: ubuntu-20.04
    needs:
      - build_frontend
      - build_backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven

      - name: Download frontend assets
        uses: actions/download-artifact@v2
        with:
          name: frontend-assets
          path: backend/sirius-web-frontend/src/main/resources/static/
      - name: Build only the frontend Maven module
        # https://stackoverflow.com/a/3899772/4874344
        run: ./mvnw package -pl sirius-web-frontend
        working-directory: backend/

      - run: mkdir staging
      - name: Download the backend JAR
        uses: actions/download-artifact@v2
        with:
          name: sirius-web-backend
          path: staging/

      - name: Remove previous individual artifacts
        # Helps keep the list of artifacts clean. They are not needed anyway
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            sirius-web-backend
            frontend-assets

      - name: Inject frontend assets into the JAR
        # Injecting files into JAR using zip: https://stackoverflow.com/a/4799569/4874344
        run: |
          mkdir -p BOOT-INF/lib
          find backend/sirius-web-frontend/target -maxdepth 1 -name "*.jar" -not -name "*-sources.jar" -exec mv {} BOOT-INF/lib/ \;
          zip -r --compression-method=store staging/sirius-web-application.jar BOOT-INF/lib

      - name: Upload the final application JAR
        uses: actions/upload-artifact@v2
        with:
          name: sirius-web-application
          path: staging/
