name: Build
on: [push, pull_request]

jobs:
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install packages in the root of the repository
        working-directory: ./
        run: npm install
      - name: Set GitHub Packages registry token
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run format-lint
      # There are no tests yet
      # - run: npm run ci-test
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-assets
          path: build/

  build_backend:
    name: Build backend
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend
    needs: build_frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - uses: actions/download-artifact@v2
        with:
          name: frontend-assets
          path: sirius-web-frontend/src/main/resources/static/
      - name: Build with Maven
        env:
          GITHUB_PACKAGES_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw --batch-mode --update-snapshots package --settings settings.xml
      - run: |
          mkdir staging
          find sirius-web-sample-application/target -maxdepth 1 -name "*.jar" -not -name "*-sources.jar" -exec cp {} staging/sirius-web-application.jar \;
      - uses: actions/upload-artifact@v2
        with:
          name: sirius-web-application
          path: staging/
