name: Git Hygiene Checks
on: [pull_request]

jobs:
  block-fixup:
    name: Block fixup commits
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: 13rac1/block-fixup-merge-action@v2.0.0
