name: Build paper
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "paper/**"

jobs:
  build_paper:
    name: Build paper
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper/test.tex
          working_directory: paper/
      - run: ls .
      - run: ls paper
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v2
        with:
          name: thesis-paper
          path: paper/test.pdf
