name: Build thesis paper
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "paper/**"

jobs:
  build_paper:
    name: Build thesis paper
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: EE-dyplom.tex
          working_directory: paper/
          latexmk_use_xelatex: true
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v2
        with:
          name: thesis-paper
          path: paper/EE-dyplom.pdf
